apiVersion: v1
kind: Service
metadata:
  labels:
    name: westernwall-redis
  name: westernwall-redis-svc
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: westernwall-redis
